# Generated by Django 3.0.8 on 2020-08-16 19:56

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200815_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_avatar',
            field=smartfields.fields.ImageField(null=True, upload_to='user_avatar/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, upload_to='user_avatar'),
        ),
    ]
