# Generated by Django 3.0.8 on 2020-08-17 06:33

import authapp.models
from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200817_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, upload_to=authapp.models.avatar_image_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_avatar',
            field=smartfields.fields.ImageField(null=True, upload_to=authapp.models.avatar_image_upload_path),
        ),
    ]
