# Generated by Django 3.0.8 on 2020-08-17 07:32

import authapp.models
from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200817_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_avatar',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(null=True, upload_to=authapp.models.avatar_image_upload_path),
        ),
    ]
