# Generated by Django 3.0.8 on 2020-08-17 07:34

import authapp.models
from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200817_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, default='static/user-bg.jpg', upload_to=authapp.models.avatar_image_upload_path),
        ),
    ]
